name: docbuddy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  http: ^1.2.1
  path_provider: ^2.1.3
  pdf: ^3.10.8
  open_file: ^3.3.2
  logger: ^2.2.0
  lottie: ^3.3.1
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon.png"

# ⛔ Disable native splash screen so Lottie animation shows only
flutter_native_splash:
  android: false
  ios: false

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/animation/health_loading.json
